tasks:
  - name: Install and Start DDEV
    before: |
      export DDEV_NONINTERACTIVE=true
      curl -fsSL https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh | bash
      ddev version
    init: |
      ddev start || true
      npm install
      npm run build:css
      npm run build:js
      composer install

ports:
  - port: 8080
    onOpen: open-browser