title: Default Page

columns:
    main:
        width: 2/3
        sections:
            fields:
                type: fields
                fields:
                    subline:
                        type: text
                        label: Zwischenüberschrift
                    text:
                        type: textarea
                        size: huge

    sidebar:
        width: 1/3
        sections:
            pages:
                type: pages
                template: default
            files:
                type: files
