title: Default Page

columns:
    main:
        width: 2/3
        sections:
            fields:
                type: fields
                fields:
                    banner:
                        label: Bild
                        type: files
                        multiple: false
                        layout: cards
                        image:
                            cover: true
                            ratio: 16/9
                    subline:
                        type: text
                        label: Überschrift
                    text:
                        type: textarea
                        size: huge

    sidebar:
        width: 1/3
        sections:
            pages:
                type: pages
                template: default
            files:
                type: files
