title: Default Page

sections:
    content:
        type: fields
        fields:
            banner:
                label: Banner
                type: files
                multiple: false
                query: page('pictures').pictures.toFiles
                layout: cards
                image:
                    cover: true
                    ratio: 16/9
                uploads: false
            subline:
                type: text
                label: Überschrift
            block:
                type: blocks
                label: Inhalt
                pretty: false
                fieldsets:
                    text:
                        label: Text
                        type: group
                        fieldsets:
                            - heading
                            - text
                            - list
                    media:
                        label: Media
                        type: group
                        fieldsets:
                            - image
                    misc:
                        label: Verschiedenes
                        type: group
                        fieldsets:
                            - table
                            - line
                            - markdown
