title: Site

tabs:
    home:
        label: Startseite
        icon: home
        columns:
            left:
                width: 1/2
                fields:
                    contact:
                        label: Kontakt
                        type: textarea
                        size: small
                        buttons: true

            right:
                width: 1/2
                fields:
                    news:
                        label: Neuigkeiten
                        type: textarea
                        size: small
                        buttons: true
                    toggleWheater:
                        label: Wetter anzeigen
                        type: toggle

    images:
        label: Zufallsbilder
        icon: image
        columns:
            center:
                width: 1/1
                fields:
                    files:
                        type: files
                        label: Zufallsbilder
                        layout: cards
                        size: small
                        image:
                            cover: true
                            ratio: 16/9

    pages:
        label: Seiten
        icon: document
        columns:
            left:
                width: 2/3
                sections:
                    published:
                        type: pages
                        status: listed
                        headline: Veröffentlichte Seiten
                        layout: cards
                        image:
                            cover: true
                        size: medium

            right:
                width: 1/3
                sections:
                    unlisted:
                        type: pages
                        headline: Nicht gelistete Seiten
                        status: unlisted
                        layout: cardlets

                    drafts:
                        type: pages
                        headline: Entwürfe
                        create: default
                        status: draft
                        layout: cards
                        image:
                            cover: true
                        size: tiny

    settings:
        label: Einstellungen
        icon: settings
        columns:
            left:
                width: 1/2
                fields:
                    toggleContact:
                        label: Kontakt-Box anzeigen
                        type: toggle
                    toggleQuotes:
                        label: Zitat-Box anzeigen
                        type: toggle
                    toggleEvent:
                        label: Termin-Box anzeigen
                        type: toggle

            right:
                width: 1/2
                fields:
                    email:
                        label: E-Mail-Adresse
                        type: email
                        buttons: false
                    phone:
                        label: Telefonnummer
                        type: tel
                        buttons: false
                    description:
                        label: Seiten-Beschreibung
                        type: textarea
                        size: medium
                        buttons: false
